INSERT INTO exercicio (uuid, nome, descricao, musculo)
VALUES (gen_random_uuid(), 'Extensão Lombar',
        'Execução de extensão lombar para fortalecimento da região inferior das costas.', 'COSTAS'),
       (gen_random_uuid(), 'Good Morning (Bom dia) com Faixa Elástica',
        'Movimento de flexão e extensão do tronco utilizando faixa elástica para resistência.', 'COSTAS'),
       (gen_random_uuid(), 'Levantamento Terra na Polia',
        'Execução de levantamento terra usando polia para resistência controlada.', 'COSTAS'),
       (gen_random_uuid(), 'Levantamento Terra (Deadlift)',
        'Movimento clássico de levantamento de peso para costas e pernas.', 'COSTAS'),
       (gen_random_uuid(), 'Levantamento Terra com Halteres', 'Versão do levantamento terra utilizando halteres.',
        'COSTAS'),
       (gen_random_uuid(), 'Levantamento Terra Romeno com Halteres',
        'Levantamento terra romeno realizado com halteres para foco nos isquiotibiais e lombar.', 'COSTAS'),
       (gen_random_uuid(), 'Good Morning (Bom dia)', 'Exercício de flexão e extensão do tronco com barra nas costas.',
        'COSTAS'),
       (gen_random_uuid(), 'Hiperextensão no Banco',
        'Execução de hiperextensão utilizando banco específico para lombar.', 'COSTAS'),
       (gen_random_uuid(), 'Extensão Lombar Deitado', 'Movimento de extensão lombar realizado na posição deitado.',
        'COSTAS'),
       (gen_random_uuid(), 'Levantamento Terra com Faixa de Resistência',
        'Variante do levantamento terra utilizando faixa elástica.', 'COSTAS'),
       (gen_random_uuid(), 'Levantamento Terra Romeno',
        'Versão do levantamento terra focada nos isquiotibiais e lombar.', 'COSTAS'),
       (gen_random_uuid(), 'Extensão Lombar Sentado', 'Execução de extensão lombar na posição sentada.', 'COSTAS'),
       (gen_random_uuid(), 'Good Morning (Bom dia) Sentado', 'Variante do good morning realizado na posição sentada.',
        'COSTAS'),
       (gen_random_uuid(), 'Extensão Lombar na Bola de Estabilidade', 'Execução de extensão lombar sobre bola suíça.',
        'COSTAS'),
       (gen_random_uuid(), 'Levantamento Terra Sumo', 'Variante do levantamento terra com afastamento amplo dos pés.',
        'COSTAS'),
       (gen_random_uuid(), 'Barra Fixa Assistida',
        'Execução de barra fixa com auxílio de máquina para reduzir carga corporal.', 'COSTAS'),
       (gen_random_uuid(), 'Puxada na Polia (Lat Pulldown)',
        'Puxada na polia alta para fortalecimento do grande dorsal.', 'COSTAS'),
       (gen_random_uuid(), 'Barra Fixa com Pegada Neutra (Hammer Grip)', 'Execução de barra fixa com pegada neutra.',
        'COSTAS'),
       (gen_random_uuid(), 'Puxada no Aparelho', 'Puxada utilizando máquina específica para costas.', 'COSTAS'),
       (gen_random_uuid(), 'Puxada Atrás da Cabeça na Polia',
        'Variante de puxada na polia posicionando a barra atrás da cabeça.', 'COSTAS'),
       (gen_random_uuid(), 'Barra Fixa Atrás da Cabeça', 'Execução de barra fixa levando a barra atrás da cabeça.',
        'COSTAS'),
       (gen_random_uuid(), 'Barra Fixa Tradicional', 'Execução clássica de barra fixa com pegada pronada.', 'COSTAS'),
       (gen_random_uuid(), 'Puxada com Braço Estendido (Straight Arm Pulldown)',
        'Movimento na polia com os braços estendidos para isolar dorsais.', 'COSTAS'),
       (gen_random_uuid(), 'Barra Fixa com Pegada Aberta',
        'Execução de barra fixa com pegada aberta para foco nos dorsais.', 'COSTAS'),
       ('393f8ef4-4092-48cf-8603-a1d201bccd18',
        'Deitado no banco reto, empurre a barra do peito à extensão completa e retorne controlando.', 'PEITO',
        'Supino Reto com Barra'),
       ('66ceb00c-c3ab-4d69-960e-b98587b38f9a',
        'Banco inclinado ~30–45°, empurre halteres e feche no topo, controle na descida.', 'PEITO',
        'Supino Inclinado com Halteres'),
       ('f5e8c3c7-7630-4221-977c-a27e755ef948',
        'Aberturas no banco reto com leve flexão nos cotovelos, foco na amplitude.', 'PEITO', 'Crucifixo com Halteres'),
       ('66484fd7-5500-4fcc-8991-9b90a48bf07b',
        'Adução horizontal no crossover, postura firme e pico de contração no centro.', 'PEITO', 'Cross-over no Cabo'),
       ('edf4ad40-6e57-4c1b-86a2-b8ce655d31da',
        'Deitado, flexione e estenda os cotovelos trazendo a barra em direção à testa.', 'PEITO',
        'Tríceps Testa (Skull Crusher)'),
       ('a1c61508-ead8-4b43-aa39-cc403603e791', 'Apoio nas paralelas, desça controlado e estenda cotovelos até travar.',
        'PEITO', 'Mergulho em Paralelas'),
       ('8d79e84e-69de-42ed-b29d-b67df2d5a729', 'Extensão de cotovelos no cabo com corda, abra as pontas no final.',
        'PEITO', 'Tríceps Corda no Pulley'),
       ('4b91a204-114a-4e97-a0fe-e2d789a0f43e', 'Em pé, flexione os cotovelos mantendo os braços junto ao corpo.',
        'PEITO', 'Rosca Direta com Barra'),
       ('7785d589-5387-421d-82fd-d822a0b7b7ff', 'Flexão alternada, supine o punho durante a subida.', 'PEITO',
        'Rosca Alternada com Halteres'),
       ('20639a10-ab6e-4817-adff-38e17b6d72e5', 'No banco Scott, ênfase no alongamento e controle.', 'PEITO',
        'Rosca Scott'),
       ('155087d8-48ae-4a07-98fb-a9f14c84ece2', 'Press acima da cabeça com barra, core firme.', 'PEITO',
        'Desenvolvimento Militar'),
       ('e1969d7b-9628-4c5e-b7cc-d20969f30d7f',
        'Eleve halteres até linha do ombro com cotovelos levemente flexionados.', 'PEITO', 'Elevação Lateral'),
       ('77275a04-7c35-4388-b435-f729e78de4b0', 'Eleve halteres à frente até a altura dos ombros.', 'PEITO',
        'Elevação Frontal'),
       ('573d1b54-70d2-4a45-99e9-3e5556ead9a8', 'Flexão de punhos com barra apoiada.', 'PEITO',
        'Rosca de Punho (Wrist Curl)'),
       ('500c79f7-0f5e-45f2-b5ce-410732489d80', 'Extensão de punhos com barra/halter.', 'PEITO', 'Extensão de Punho'),
       ('072b30cb-6dbb-404d-9ae7-cf49f42ba975', 'Barra ao peito, deprime escápulas e puxe com dorsais.', 'PEITO',
        'Puxada na Frente (Pulldown)'),
       ('2a0b0abc-8dcc-4c63-a913-18c98de574c5', 'Incline o tronco e puxe a barra ao abdômen.', 'PEITO',
        'Remada Curvada com Barra'),
       ('57d78224-8e0e-48ce-a8e4-dd9017849f83', 'Apoio no banco, puxe o halter ao quadril.', 'PEITO',
        'Remada Unilateral com Halter'),
       ('b6e3dc94-beba-4fe2-90b1-ae9b8b454422', 'Tire a barra do chão com cadeia posterior e costas firmes.', 'PEITO',
        'Levantamento Terra (Convencional)'),
       ('00fabac8-82f5-4ed7-9df6-b075fc40edc7', 'Eleve os ombros em direção às orelhas e desça devagar.', 'PEITO',
        'Encolhimento com Halteres'),
       ('0c4ce3ae-4d2e-44a5-9ad8-01c45db1884e', 'Variante com barra em pé, pegada neutra/larga.', 'PEITO',
        'Encolhimento na Barra'),
       ('4cc4e3e2-e80a-45ce-b5ec-04149565af3c', 'Estenda o tronco alinhando com o quadril, sem hiperextensão.', 'PEITO',
        'Extensão Lombar no Banco Romano'),
       ('a347bb2f-d835-4dcf-be78-c7faf49e3ef3', 'Flexão de quadril com barra nas costas, ênfase na lombar e isquios.',
        'PEITO', 'Good Morning'),
       ('1c15b7f7-3331-4052-b11b-78a99158221d', 'Flexão da coluna aproximando costelas do quadril, curto e controlado.',
        'PEITO', 'Crunch no Solo'),
       ('52a2b2b0-9053-4e7a-8d09-be1e8a244029', 'Deitado, eleve as pernas mantendo lombar apoiada.', 'PEITO',
        'Elevação de Pernas'),
       ('8fe8216f-5238-412a-bf05-a7aad17b8e87', 'Apoio lateral, corpo alinhado, segure tempo-alvo.', 'PEITO',
        'Prancha Lateral'),
       ('b1e155d3-33e2-43af-b95e-02a2d82047f2', 'Puxada diagonal do alto para baixo ou vice-versa.', 'PEITO',
        'Rotação no Cabo (Woodchopper)'),
       ('f22656b4-e66c-48dd-b407-cb84ce4244da', 'Apoio de antebraços, mantenha alinhamento e respiração.', 'PEITO',
        'Prancha Frontal'),
       ('2d4689c8-6fac-4f43-9ccb-776995f0dea2', 'Coordene braços e pernas mantendo lombar no solo.', 'PEITO',
        'Dead Bug'),
       ('2c11f84a-b756-4bf4-a5a8-d64ed5cacae0',
        'Joelhos semi-flexionados, foque em dobradiça de quadril e alongamento.', 'PEITO', 'Levantamento Terra Romeno'),
       ('3781d70c-3e29-48d4-ab3f-cb1a25a2006e', 'Elevação de quadril com costas no banco, contraia no topo.', 'PEITO',
        'Hip Thrust'),
       ('43dbd284-b787-44be-8281-8bcac80681ae', 'Base ampla e pés abduzidos, desça mantendo joelhos alinhados.',
        'PEITO', 'Agachamento Sumô'),
       ('bae067a9-f86d-4643-ad27-2f4ae2a8feba', 'Desça até a paralela mantendo coluna neutra e suba empurrando o chão.',
        'PEITO', 'Agachamento Livre'),
       ('ca5fedaa-bdcc-4d79-8fea-ca65840feb3d', 'Empurre a plataforma controlando descida e amplitude.', 'PEITO',
        'Leg Press'),
       ('f12de25e-590c-4099-ba57-9a696c4d5bcc', 'Extensão de joelhos com controle, ênfase no pico.', 'PEITO',
        'Cadeira Extensora'),
       ('c1a9e14b-36cb-4b7c-9ee1-cb31b0e55481', 'Flexione joelhos aproximando calcanhares dos glúteos.', 'PEITO',
        'Mesa Flexora'),
       ('b1b71dcc-bbb8-459b-8829-322682ffe6a6', 'Dobradiça de quadril, desça mantendo barra/halteres perto do corpo.',
        'PEITO', 'Stiff com Halteres'),
       ('aa578115-bbae-4389-b521-94b74a325236', 'Suba na ponta dos pés e desça devagar com amplitude total.', 'PEITO',
        'Elevação de Gêmeos em Pé'),
       ('d35e5539-9234-42e9-adb0-67f5b2d28645', 'Foco no sóleo; subida e descida controladas.', 'PEITO',
        'Elevação de Gêmeos Sentado'),
       ('b32c7be3-bd56-4683-9b04-a79ca42a9abf', 'Aproxime as pernas contra resistência, controle retorno.', 'PEITO',
        'Cadeira Adutora'),
       ('9793c24d-6b44-4c6d-bb7f-a37b99b22d04', 'Passada ampla enfatizando adutores.', 'PEITO',
        'Passada Sumô com Halter'),
       ('6a886931-037d-4aaf-a5f1-c4dc797fd3e1', 'Afaste as pernas contra resistência, controle retorno.', 'PEITO',
        'Cadeira Abdutora'),
       ('847af8e3-123f-4bcf-9a05-c8695718f516', 'Em pé, abra a perna lateralmente com miniband.', 'PEITO',
        'Abdução de Quadril com Faixa') ON CONFLICT (nome, musculo, descricao) DO NOTHING;
;

INSERT INTO exercicio (uuid, nome, descricao, musculo)
VALUES (gen_random_uuid(), 'Mergulho no Banco', 'Mergulho usando banco, ativando peitoral com controle no movimento.',
        'PEITO'),
       (gen_random_uuid(), 'Supino Reto com Barra', 'Supino reto com barra, força no peitoral mantendo tronco firme.',
        'PEITO'),
       (gen_random_uuid(), 'Crucifixo com Cabo', 'Crucifixo executado com cabo em estação, amplitude controlada.',
        'PEITO'),
       (gen_random_uuid(), 'Supino na Máquina', 'Pressão na máquina com foco no peitoral, braços alinhados.', 'PEITO'),
       (gen_random_uuid(), 'Supino Reto Fechado com Barra',
        'Supino com pegada fechada na barra, enfatiza triceps e peitoral interno.', 'PEITO'),
       (gen_random_uuid(), 'Supino Declinado com Barra',
        'Supino declinado com barra, ativando parte inferior do peitoral.', 'PEITO'),
       (gen_random_uuid(), 'Supino Declinado com Halteres',
        'Supino declinado com halteres, controle na descida e subida.', 'PEITO'),
       (gen_random_uuid(), 'Crucifixo Declinado com Halteres',
        'Crucifixo em banco declinado, foco no peitoral inferior.', 'PEITO'),
       (gen_random_uuid(), 'Flexões Declinado', 'Flexões com pés elevados, maior intensidade no peitoral superior.',
        'PEITO'),
       (gen_random_uuid(), 'Barra Paralela para Peitoral',
        'Mergulho em barras paralelas, alta ativação do peitoral e triceps.', 'PEITO'),
       (gen_random_uuid(), 'Supino com Halteres', 'Supino reto com halteres, amplitude maior e maior estabilização.',
        'PEITO'),
       (gen_random_uuid(), 'Crucifixo no Chão com Halteres',
        'Crucifixo executado no chão, amplitude limitada para segurança.', 'PEITO'),
       (gen_random_uuid(), 'Crucifixo com Halteres',
        'Crucifixo convencional com halteres, abertura controlada dos braços.', 'PEITO'),
       (gen_random_uuid(), 'Supino Inclinado com Barra', 'Supino inclinado com barra, enfatiza peitoral superior.',
        'PEITO'),
       (gen_random_uuid(), 'Crucifixo Inclinado com Cabo', 'Crucifixo inclinado usando cabo, amplitude ascendente.',
        'PEITO'),
       (gen_random_uuid(), 'Supino Inclinado na Máquina',
        'Pressão inclinada na máquina, foco no peitoral superior com estabilidade.', 'PEITO'),
       (gen_random_uuid(), 'Crucifixo Inclinado com Halteres',
        'Crucifixo inclinado com halteres, amplitude e controle ascendente.', 'PEITO'),
       (gen_random_uuid(), 'Supino Inclinado com Halteres',
        'Supino inclinado com halteres, ângulo para trabalhar peitoral superior.', 'PEITO'),
       (gen_random_uuid(), 'Crucifixo na Máquina', 'Crucifixo na máquina “pec deck”, isolando os peitorais.', 'PEITO'),
       (gen_random_uuid(), 'Pullover', 'Pullover no banco, ativa peitoral e dorsais ao estender os braços.', 'PEITO'),
       (gen_random_uuid(), 'Flexão Tradicional', 'Flexão de braço convencional, peso corporal, peitoral e core ativos.',
        'PEITO'),
       (gen_random_uuid(), 'Flexão sobre Bola',
        'Flexão com mãos sobre bola, instabilidade aumenta ativação do peitoral.', 'PEITO'),
       (gen_random_uuid(), 'Supino com Faixa Elástica',
        'Pressão com faixa elástica, resistência progressiva do peitoral.',
        'PEITO') ON CONFLICT (nome, musculo, descricao) DO NOTHING;

INSERT INTO exercicio (descricao, musculo, nome)
VALUES ('Extensão de cotovelo deitado, descendo a barra até a testa e subindo controlado.', 'TRICEPS',
        'Tríceps Testa com Barra'),
       ('Extensão unilateral de tríceps atrás da cabeça com halter, foco no tríceps longo.', 'TRICEPS',
        'Tríceps Francês Unilateral'),
       ('Extensão de tríceps em polia alta com barra reta, mantendo cotovelos fixos.', 'TRICEPS',
        'Tríceps Pulley com Barra Reta'),
       ('Extensão de tríceps em polia alta com corda, abrindo no final do movimento.', 'TRICEPS',
        'Tríceps Pulley com Corda'),
       ('Mergulho entre bancos, descendo quadril até 90° e subindo estendendo cotovelos.', 'TRICEPS',
        'Mergulho entre Bancos'),
       ('Mergulho nas paralelas, descida controlada até 90° de cotovelo.', 'TRICEPS', 'Paralelas (Dips)'),
       ('Extensão de tríceps no crossover, pegada invertida (supinada).', 'TRICEPS', 'Tríceps Inverso no Crossover'),
       ('Extensão de tríceps kickback com halter, mantendo o tronco inclinado.', 'TRICEPS', 'Tríceps Kickback'),
       ('Extensão de tríceps testa com halteres, maior amplitude de movimento.', 'TRICEPS',
        'Tríceps Testa com Halteres'),
       ('Extensão de tríceps com elástico, em pé, puxando até extensão completa.', 'TRICEPS',
        'Tríceps com Faixa Elástica'),
       (gen_random_uuid(), 'Afaste as pernas contra resistência na máquina, mantendo postura firme.', 'ABDUTOR',
        'Cadeira Abdutora'),
       (gen_random_uuid(), 'Em pé, abra a perna lateralmente utilizando faixa elástica.', 'ABDUTOR',
        'Abdução de Quadril com Faixa Elástica'),
       (gen_random_uuid(), 'Deitado de lado, eleve a perna de cima até a linha do quadril, controlando retorno.',
        'ABDUTOR', 'Abdução de Quadril no Solo'),
       (gen_random_uuid(), 'De pé, utilize polia baixa presa ao tornozelo para afastar lateralmente a perna.',
        'ABDUTOR', 'Abdução de Quadril na Polia'),
       (gen_random_uuid(), 'Na posição de quatro apoios, abra lateralmente a perna mantendo joelhos flexionados.',
        'ABDUTOR', 'Abdução em Quatro Apoios (Cachorrinho)'),
       (gen_random_uuid(), 'De pé, execute abdução de quadril com caneleiras para resistência adicional.', 'ABDUTOR',
        'Abdução com Caneleira'),
       (gen_random_uuid(), 'Deitado de lado, utilize miniband acima dos joelhos para aumentar a resistência.',
        'ABDUTOR', 'Abdução Lateral com Miniband'),
       (gen_random_uuid(), 'De pé, com halteres segurados, realize abdução lateral da perna para fortalecimento.',
        'ABDUTOR', 'Abdução Lateral com Halteres'),
       (gen_random_uuid(), 'Eleve os ombros em direção às orelhas com barra, controlando a descida.', 'TRAPEZIO',
        'Encolhimento com Barra'),
       (gen_random_uuid(), 'Segure halteres ao lado do corpo e eleve os ombros até o máximo possível.', 'TRAPEZIO',
        'Encolhimento com Halteres'),
       (gen_random_uuid(), 'Realize encolhimento na máquina específica para trapézio, mantendo controle.', 'TRAPEZIO',
        'Encolhimento na Máquina'),
       (gen_random_uuid(), 'Segure a barra em pegada pronada e puxe até o queixo, cotovelos para cima.', 'TRAPEZIO',
        'Remada Alta com Barra'),
       (gen_random_uuid(), 'Com halteres, realize remada alta em pé, mantendo a barra próxima ao corpo.', 'TRAPEZIO',
        'Remada Alta com Halteres'),
       (gen_random_uuid(), 'Puxada com corda na polia baixa, trazendo em direção ao pescoço.', 'TRAPEZIO',
        'Face Pull na Polia'),
       (gen_random_uuid(), 'Deite no banco inclinado de bruços e eleve os ombros, segurando halteres.', 'TRAPEZIO',
        'Encolhimento Invertido no Banco Inclinado'),
       (gen_random_uuid(), 'Utilize barra hexagonal (trap bar) para encolhimento, foco na parte superior.', 'TRAPEZIO',
        'Encolhimento com Trap Bar'),
       (gen_random_uuid(), 'Pressione a barra acima da cabeça, mantendo o core firme e coluna neutra.', 'OMBRO',
        'Desenvolvimento Militar com Barra'),
       (gen_random_uuid(), 'Pressione halteres acima da cabeça, juntando no topo, sentado ou em pé.', 'OMBRO',
        'Desenvolvimento com Halteres'),
       (gen_random_uuid(), 'Variante do desenvolvimento com rotação de punhos durante a subida.', 'OMBRO',
        'Desenvolvimento Arnold'),
       (gen_random_uuid(), 'Eleve halteres lateralmente até a altura dos ombros, controle na descida.', 'OMBRO',
        'Elevação Lateral com Halteres'),
       (gen_random_uuid(), 'Eleve a barra ou halteres à frente até a linha dos ombros, tronco firme.', 'OMBRO',
        'Elevação Frontal'),
       (gen_random_uuid(),
        'Com halteres apoiados no banco inclinado, eleve lateralmente para focar deltoide posterior.', 'OMBRO',
        'Crucifixo Invertido no Banco'),
       (gen_random_uuid(), 'Segure a corda na polia baixa e puxe lateralmente até a linha dos ombros.', 'OMBRO',
        'Elevação Lateral na Polia'),
       (gen_random_uuid(), 'Remada alta com pegada fechada, cotovelos altos, ativando deltoides e trapézio.', 'OMBRO',
        'Remada Alta'),
       (gen_random_uuid(), 'Face pull com corda na polia, puxando em direção ao rosto, foco em deltoide posterior.',
        'OMBRO', 'Face Pull'),
       (gen_random_uuid(), 'Pressão acima da cabeça usando máquina, maior estabilidade e segurança.', 'OMBRO',
        'Desenvolvimento na Máquina'),
       (gen_random_uuid(),
        'Flexione os punhos segurando barra com pegada supinada, apoiando antebraços nos joelhos ou banco.',
        'ANTEBRACO', 'Rosca de Punho com Barra'),
       (gen_random_uuid(), 'Extenda os punhos segurando barra em pegada pronada, apoiando antebraços.', 'ANTEBRACO',
        'Extensão de Punho com Barra'),
       (gen_random_uuid(), 'Com halteres, flexione os punhos em posição neutra para fortalecer o antebraço.',
        'ANTEBRACO', 'Flexão de Punho com Halteres'),
       (gen_random_uuid(), 'Em pé, segure halteres pesados e caminhe determinada distância, foco na pegada.',
        'ANTEBRACO', 'Farmer Walk'),
       (gen_random_uuid(), 'Pendure-se em barra fixa pelo maior tempo possível, ativando força de pegada.', 'ANTEBRACO',
        'Barra Fixa Isométrica'),
       (gen_random_uuid(),
        'Use rolo de punho com corda e peso, enrolando e desenrolando para fortalecer extensores e flexores.',
        'ANTEBRACO', 'Wrist Roller (Rolo de Punho)'),
       (gen_random_uuid(), 'Flexione os dedos segurando barra ou halteres para desenvolver força de pegada.',
        'ANTEBRACO', 'Rosca de Dedos'),
       (gen_random_uuid(), 'Segure um halter apenas com a ponta dos dedos, trabalhando resistência e força.',
        'ANTEBRACO', 'Pinça com Halteres');